/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkerExpensesRouteImport } from './routes/_authenticated.worker.expenses'
import { Route as AuthenticatedWorkerDeliveriesRouteImport } from './routes/_authenticated.worker.deliveries'
import { Route as AuthenticatedWorkerDashboardRouteImport } from './routes/_authenticated.worker.dashboard'
import { Route as AuthenticatedWorkerCustomersRouteImport } from './routes/_authenticated.worker.customers'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated.admin.notifications'
import { Route as AuthenticatedAdminLotsRouteImport } from './routes/_authenticated.admin.lots'
import { Route as AuthenticatedAdminExpensesRouteImport } from './routes/_authenticated.admin.expenses'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated.admin.dashboard'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated.admin.customers'
import { Route as AuthenticatedAdminBillsRouteImport } from './routes/_authenticated.admin.bills'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkerExpensesRoute =
  AuthenticatedWorkerExpensesRouteImport.update({
    id: '/worker/expenses',
    path: '/worker/expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkerDeliveriesRoute =
  AuthenticatedWorkerDeliveriesRouteImport.update({
    id: '/worker/deliveries',
    path: '/worker/deliveries',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkerDashboardRoute =
  AuthenticatedWorkerDashboardRouteImport.update({
    id: '/worker/dashboard',
    path: '/worker/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkerCustomersRoute =
  AuthenticatedWorkerCustomersRouteImport.update({
    id: '/worker/customers',
    path: '/worker/customers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLotsRoute = AuthenticatedAdminLotsRouteImport.update({
  id: '/admin/lots',
  path: '/admin/lots',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminExpensesRoute =
  AuthenticatedAdminExpensesRouteImport.update({
    id: '/admin/expenses',
    path: '/admin/expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/admin/customers',
    path: '/admin/customers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBillsRoute = AuthenticatedAdminBillsRouteImport.update({
  id: '/admin/bills',
  path: '/admin/bills',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/bills': typeof AuthenticatedAdminBillsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/lots': typeof AuthenticatedAdminLotsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/worker/customers': typeof AuthenticatedWorkerCustomersRoute
  '/worker/dashboard': typeof AuthenticatedWorkerDashboardRoute
  '/worker/deliveries': typeof AuthenticatedWorkerDeliveriesRoute
  '/worker/expenses': typeof AuthenticatedWorkerExpensesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/bills': typeof AuthenticatedAdminBillsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/lots': typeof AuthenticatedAdminLotsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/worker/customers': typeof AuthenticatedWorkerCustomersRoute
  '/worker/dashboard': typeof AuthenticatedWorkerDashboardRoute
  '/worker/deliveries': typeof AuthenticatedWorkerDeliveriesRoute
  '/worker/expenses': typeof AuthenticatedWorkerExpensesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin/bills': typeof AuthenticatedAdminBillsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/_authenticated/admin/lots': typeof AuthenticatedAdminLotsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/worker/customers': typeof AuthenticatedWorkerCustomersRoute
  '/_authenticated/worker/dashboard': typeof AuthenticatedWorkerDashboardRoute
  '/_authenticated/worker/deliveries': typeof AuthenticatedWorkerDeliveriesRoute
  '/_authenticated/worker/expenses': typeof AuthenticatedWorkerExpensesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/bills'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/expenses'
    | '/admin/lots'
    | '/admin/notifications'
    | '/worker/customers'
    | '/worker/dashboard'
    | '/worker/deliveries'
    | '/worker/expenses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/bills'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/expenses'
    | '/admin/lots'
    | '/admin/notifications'
    | '/worker/customers'
    | '/worker/dashboard'
    | '/worker/deliveries'
    | '/worker/expenses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin/bills'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/expenses'
    | '/_authenticated/admin/lots'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/worker/customers'
    | '/_authenticated/worker/dashboard'
    | '/_authenticated/worker/deliveries'
    | '/_authenticated/worker/expenses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/worker/expenses': {
      id: '/_authenticated/worker/expenses'
      path: '/worker/expenses'
      fullPath: '/worker/expenses'
      preLoaderRoute: typeof AuthenticatedWorkerExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/worker/deliveries': {
      id: '/_authenticated/worker/deliveries'
      path: '/worker/deliveries'
      fullPath: '/worker/deliveries'
      preLoaderRoute: typeof AuthenticatedWorkerDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/worker/dashboard': {
      id: '/_authenticated/worker/dashboard'
      path: '/worker/dashboard'
      fullPath: '/worker/dashboard'
      preLoaderRoute: typeof AuthenticatedWorkerDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/worker/customers': {
      id: '/_authenticated/worker/customers'
      path: '/worker/customers'
      fullPath: '/worker/customers'
      preLoaderRoute: typeof AuthenticatedWorkerCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/lots': {
      id: '/_authenticated/admin/lots'
      path: '/admin/lots'
      fullPath: '/admin/lots'
      preLoaderRoute: typeof AuthenticatedAdminLotsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/expenses': {
      id: '/_authenticated/admin/expenses'
      path: '/admin/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AuthenticatedAdminExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/bills': {
      id: '/_authenticated/admin/bills'
      path: '/admin/bills'
      fullPath: '/admin/bills'
      preLoaderRoute: typeof AuthenticatedAdminBillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminBillsRoute: typeof AuthenticatedAdminBillsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminExpensesRoute: typeof AuthenticatedAdminExpensesRoute
  AuthenticatedAdminLotsRoute: typeof AuthenticatedAdminLotsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedWorkerCustomersRoute: typeof AuthenticatedWorkerCustomersRoute
  AuthenticatedWorkerDashboardRoute: typeof AuthenticatedWorkerDashboardRoute
  AuthenticatedWorkerDeliveriesRoute: typeof AuthenticatedWorkerDeliveriesRoute
  AuthenticatedWorkerExpensesRoute: typeof AuthenticatedWorkerExpensesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminBillsRoute: AuthenticatedAdminBillsRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminExpensesRoute: AuthenticatedAdminExpensesRoute,
  AuthenticatedAdminLotsRoute: AuthenticatedAdminLotsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedWorkerCustomersRoute: AuthenticatedWorkerCustomersRoute,
  AuthenticatedWorkerDashboardRoute: AuthenticatedWorkerDashboardRoute,
  AuthenticatedWorkerDeliveriesRoute: AuthenticatedWorkerDeliveriesRoute,
  AuthenticatedWorkerExpensesRoute: AuthenticatedWorkerExpensesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
